apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "mediasoup-broadcast-example.fullname" . }}
  labels:
    app: {{ template "mediasoup-broadcast-example.name" . }}
    chart: {{ template "mediasoup-broadcast-example.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mediasoup-broadcast-example.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "mediasoup-broadcast-example.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: {{ .Values.service.containerPort }}
          {{- if .Values.service.hostNetworkIP }}
            - name: RTP_ANNOUNCE_IP
              value: {{ .Values.service.hostNetworkIP }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- if .Values.service.rtpPort }}
            - name: rtp
              containerPort: {{ .Values.service.rtpPort }}
              protocol: UDP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.service.hostNetworkIP }}
      hostNetwork: true
    {{- end }}
    {{- if or .Values.service.hostNetworkIP .Values.nodeSelector }}
      nodeSelector:
    {{- end }}
    {{- if .Values.service.hostNetworkIP }}
        {{ .Values.service.hostNetworkIPSelector }}: {{ .Values.service.hostNetworkIP }}
    {{- end }}
    {{- with .Values.nodeSelector }}
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
